version: '3'
services:
  redismod:
    build: ./redismod
    ports:
      - 6379:6379
  init:
    build: ./app
    depends_on:
      - redismod
    command: ['init.py', '--url', 'redis://redismod:6379']
  server:
    build: ./app
    depends_on:
      - init
    ports:
      - 5000:5000
    command: ['server.py', '--url', 'redis://redismod:6379']
  capture:
    build: ./app
    depends_on:
      - init
    # To capture from a webcam, uncomment the next lines
    # devices:
    #  - /dev/video0:/dev/video0
    # command: ['capture.py', '--url', 'redis://redismod:6379']
    command: ['capture.py', '--url', 'redis://redismod:6379', 'data/countvoncount.mp4']
   
  prometheus:
    build: ./prometheus
    ports:
      - 9090:9090
  prometheus-redistimeseries-adapter:
    image: redislabs/prometheus-redistimeseries-adapter:master
    # TODO: freeze version
    depends_on:
      - prometheus
    ports:
      - 9201:9201
    command: ['-redis-address', 'redismod:6379', '-web.listen-address', '0.0.0.0:9201']
  grafana:
    build: ./grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
