FROM redislabs/redistimeseries:edge as timeseries
FROM redislabs/redisgears:edge as gears
FROM redisai/redisai:edge-gpu as ai

ENV LD_LIBRARY_PATH /usr/lib/redis/modules

COPY --from=gears /var/opt/redislabs/* /var/opt/redislabs/
COPY --from=timeseries ${LD_LIBRARY_PATH}/*.so ${LD_LIBRARY_PATH}/

# ENV PYTHONPATH /usr/lib/redis/modules/deps/cpython/Lib
ENTRYPOINT ["redis-server"]
CMD ["--loadmodule", "/usr/lib/redis/modules/redisai.so", \
    "--loadmodule", "/usr/lib/redis/modules/redistimeseries.so", \
    "--loadmodule", "/var/opt/redislabs/lib/modules/redisgears.so"]

ENV DEPS "python python3-pip python3-setuptools libglib2.0-0 libsm6 libxrender1 libxext6 libgomp1"
WORKDIR /data
RUN set -ex; \
    apt-get update; \
    apt-get install -y --no-install-recommends $DEPS; \
    chmod +x /usr/lib/redis/modules/redisai.so