#!/bin/bash

if [[ ! -z $(command -v docker-compose) ]]; then
	curl -s -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
	chmod +x /usr/local/bin/docker-compose
fi
